# Generated by Django 6.0.7 on 2026-07-16 21:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('parti_politique', models.CharField(blank=True, max_length=150, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Electeur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_cni', models.CharField(max_length=20, unique=True, verbose_name='Numéro CNI')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('a_vote', models.BooleanField(default=False, verbose_name='A déjà voté')),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(default='Présidentielle 2026', max_length=100)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('est_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horodatage', models.DateTimeField(auto_now_add=True, verbose_name='Date du vote')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bokkna.candidat', verbose_name='Candidat')),
                ('electeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Bokkna.electeur', verbose_name='Électeur')),
            ],
        ),
    ]
